### ISSUE TITLE
Translate APIのドキュメント翻訳機能をPythonを使って呼び出しをした際に、登録した辞書の内容が反映されない。

### ISSUE THREAD

**Issue by AtsushiNakayama12** [googleapis/python-translate#391] opened 2022-05-12 00:18 UTC
-目的：登録した辞書内容が反映された形でPythonからTranslate APIのドキュメント翻訳機能を実行すること

-課題：ドキュメント翻訳の結果に辞書で登録した内容が反映されない

-Pythonコード
# https://github.com/googleapis/python-translate/blob/main/samples/snippets/translate_v3beta1_translate_document.py
from google.cloud import storage
from google.cloud import translate_v3beta1 as translate
import os

#認証情報
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = "[サービス アカウント キー ファイルパス]"
BUCKET_NAME = '[バケット名]' # need to create beforehand
GLOSSARY_OBJECT_NAME = '[用語集名]'
#GLOSSARY_URI = 'gs://' + BUCKET_NAME + '/' + GLOSSARY_OBJECT_NAME
GLOSSARY_URI = '[用語集のパス]'
GLOSSARY_ID = '[用語集ID]'
LOCATION = "us-central1"

def translate_document(project_id: str, file_path: str):
    trans_client = translate.TranslationServiceClient()
    parent = f"projects/{project_id}/locations/{LOCATION}"

    glossary_name = trans_client.glossary_path(project_id, LOCATION, GLOSSARY_ID)
    print(glossary_name)
    language_pair = translate.types.Glossary.LanguageCodePair(
      source_language_code='ja',
      target_language_code='en')

    gcs_source = translate.types.GcsSource(input_uri=GLOSSARY_URI)
    input_config = translate.types.GlossaryInputConfig(gcs_source=gcs_source)
    glossary = translate.types.Glossary(
        name=glossary_name,
        language_pair=language_pair,
        input_config=input_config)

    #project_location_path = trans_client.location_path(project_id, LOCATION)
    glossary_create_operation = trans_client.create_glossary(
        parent=parent, 
        glossary=glossary
    )
    glossary_create_result = glossary_create_operation.result(timeout=90)
    print(glossary_create_result)

    glossary_config = translate.types.TranslateTextGlossaryConfig(
      glossary=glossary_name
    )

    # Supported file types: https://cloud.google.com/translate/docs/supported-formats
    with open(file_path, "rb") as document:
        document_content = document.read()

    document_input_config = {
        "content": document_content,
        "mime_type": "application/pdf",
    }

    response = trans_client.translate_document(
        request={
            "parent": parent,
            "source_language_code": "ja-JP",
            "target_language_code": "en-US",
            "document_input_config": document_input_config,
            "glossary_config": glossary_config
        }
    )

    with open('sample-output.pdf', 'wb') as f:     
      f.write(response.document_translation.byte_stream_outputs[0])
    #f = open('./sample-output', 'wb')
    #f.write(response.document_translation.byte_stream_outputs)
      f.close()

    # If not provided in the TranslationRequest, the translated file will only be returned through a byte-stream
    # and its output mime type will be the same as the input file's mime type
    print("Response: Detected Language Code - {}".format(response.document_translation.detected_language_code))

    # 用語集リソースを削除する
    glossary_delete_operation = trans_client.delete_glossary(name=glossary_name)

    # 用語集リソースの削除完了を待つ
    glossary_delete_result = glossary_delete_operation.result(timeout=90)

translate_document("[プロジェクトID]", '[ドキュメントパス]')

**Comment by parthea** [comment] 2022-07-29 18:20
I believe this issue is regarding a problem with the sample code in `translate_v3beta1_translate_document.py`. This appears to be the same problem described in #418. Closing as duplicate of #418
```
with open('sample-output.pdf', 'wb') as f:     
  f.write(response.document_translation.byte_stream_outputs[0])
#f = open('./sample-output', 'wb')
#f.write(response.document_translation.byte_stream_outputs)
```

**Closed by parthea** 2022-07-29 18:20 UTC
Labels: type: bug, priority: p2, api: translate
